// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTW6D5WoUS-EFpwE6McBmF9uhlBr97sY',
    appId: '1:243860568975:web:5316073f83f71b142429fa',
    messagingSenderId: '243860568975',
    projectId: 'treasury-v1',
    authDomain: 'treasury-v1.firebaseapp.com',
    storageBucket: 'treasury-v1.appspot.com',
    measurementId: 'G-1HDXQQDHEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZH4wGedU3zkJOrQbK1U5-681lb7t5Q4',
    appId: '1:243860568975:android:32045171a222e70c2429fa',
    messagingSenderId: '243860568975',
    projectId: 'treasury-v1',
    storageBucket: 'treasury-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW4KgRUxPg8lKNbOc9z_-7HciTqmunLuw',
    appId: '1:243860568975:ios:aa9ce65242e116362429fa',
    messagingSenderId: '243860568975',
    projectId: 'treasury-v1',
    storageBucket: 'treasury-v1.appspot.com',
    iosClientId: '243860568975-dc5mnedol26g5aesr39tm5k2tpnlu8kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.treasury',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW4KgRUxPg8lKNbOc9z_-7HciTqmunLuw',
    appId: '1:243860568975:ios:aa9ce65242e116362429fa',
    messagingSenderId: '243860568975',
    projectId: 'treasury-v1',
    storageBucket: 'treasury-v1.appspot.com',
    iosClientId: '243860568975-dc5mnedol26g5aesr39tm5k2tpnlu8kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.treasury',
  );
}
